### ISSUE TITLE
Error: docId and commit are required in order to apply commit

### ISSUE THREAD

**Issue by migrenaa** [ceramicstudio/3id-connect#10]
It fails on setDIDProvider. The 3idconnect version is alpha 11 but it was also failing with alpha 6.
If you need more details you can see the code here: https://github.com/DistributedTown/distributed-town-skill-wallet/tree/skill-wallet-ref

```
const [ceramic, provider] = await Promise.all([ceramicPromise, getProvider()])
  console.log('1');
  await ceramic.setDIDProvider(provider)
  console.log('2');
  const idx = createIDX(ceramic)
```

![image](https://user-images.githubusercontent.com/20582132/104735745-a60d0680-574a-11eb-907b-be03d080fc1b.png)

**Comment by oed** [comment]
@PaulLeCam @zachferland Looks like it's using `applyRecord` somewhere. We tried to make this as a non breaking change, but I think the parameter name of the `record` endpoint was changed accidentally. I think this can be fixed if we make sure to use the latest `@ceramicnetwork/http-client` everywhere.

**Comment by zachferland** [comment]
yeah this seems to likely be the case, yesterday seems like some sub dependencies were pulling in older versions, ie i had type issues when building originally, then just explicitly install latest ceramic/common, and everything appeared to work locally. Wondering if build deployed had diff dependencies again, but it build without issue. Will have to confirm infra is entirely up to date as well.

**Comment by zachferland** [comment]
ok seems like chat earlier in discord related to this as well (versioning / ceramic/common), but may or may not be related to this here
