### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by zachferland** [ceramicstudio/3id-connect#145]
Includes modal app

**Comment by Sterahi** [comment]
From Basic UI Improvements: 
- transitioned to CRA
- Updated Font to use Segment
- Do not delay before displaying the modal, instead display right away
- Display updates:
    - Default Positioning to center
    - allow opacity to be set (functionality for it is there, not usable until 3id-connect passes config object).
    - Allow users to set color (functionality for it is there, not usable until 3id-connect passes config object).
    - Display requested permissions (hard coded, but easily updated with the above once OCAPs or something similar is set up)

Advanced UI Improvements: 
- Display App domain to minimize Phishing risk.
- improved visibility animations.
