### ISSUE TITLE
Authereum - Invalid proof for signed commit

### ISSUE THREAD

**Issue by pvanroos** [ceramicstudio/3id-connect#15]
After authenticating with Authereum, I'm getting '{"error":"Invalid proof for signed commit"}' after the POST to https://ceramic-clay.3boxlabs.com/api/v0/commits.  This happens right after my code calls this:  'await ceramic.setDIDProvider(provider)'.

Code:

`const ethProvider = await web3Modal.connect()`
`const addresses = await ethProvider.enable()`
`const authProvider = new EthereumAuthProvider(ethProvider, addresses[0])`
`threeIdConnect = new ThreeIdConnect()`
`await threeIdConnect.connect(authProvider)`
`const didProvider = await threeIdConnect.getDidProvider()`

Steps to reproduce:

1. At web3Modal.connect(), browser opens second windows with Authereum login.
2. Login with Authereum login (on Mainnet).
3. In popup window, a new page is loaded with prompt to 'Sign Message':  "Create a new account link to your identity. did:3:xxx Timestamp: 1611281995".  Click 'Sign'
4. After clicking Sign, window closes. Popup (like a toast) pops up inside of first browser (where code is executing) with message: Signed Message "Create a new account link to your identity. did:3:xxx, Timestamp: xx"  6:20pm.  I close it.
5. Another message inside first browser window pops and says 'Signed message: Add this account as a Ceramic authentication message."  I close this.
6. In browser console, an error throws with: I'm getting '{"error":"Invalid proof for signed commit"}' after the POST to https://ceramic-clay.3boxlabs.com/api/v0/commits. 

Package versions:

+-- 3id-connect@1.0.0-alpha15
+-- 3id-did-provider@0.5.0
+-- @ceramicnetwork/core@0.19.2
+-- @ceramicnetwork/http-client@0.9.5
+-- @ceramicstudio/idx@0.7.0
+-- @portis/web3@3.0.3
+-- @stablelib/random@1.0.0
+-- @testing-library/jest-dom@5.11.9
+-- @testing-library/react@11.2.3
+-- @testing-library/user-event@12.6.0
+-- @walletconnect/web3-provider@1.3.4
+-- authereum@0.1.0
+-- bootstrap@4.6.0
+-- fortmatic@2.2.1
+-- UNMET PEER DEPENDENCY jquery@1.9.1 - 3
+-- key-did-provider-ed25519@1.0.0
+-- UNMET PEER DEPENDENCY popper.js@^1.16.1
+-- react@17.0.1
+-- react-bootstrap@1.4.3
+-- react-dom@17.0.1
+-- react-scripts@4.0.1
+-- web-vitals@1.1.0
`-- web3modal@1.9.3

**Comment by pvanroos** [comment]
I need to expand this. I tried authenticating with just Metamask using the ThreeIdConnect object.  It's not working either.  The error occurs after attempting to execute this:  await ceramic.setDIDProvider(provider)

TypeError: Cannot read property 'did:key:z6Mko3QByeMqTihDJNUrTBbDKdJV2JMnabE1DfRLQfxfdxBs' of undefined
    at t.ThreeIDX.<anonymous> (index.js:49)
    at Generator.next (<anonymous>)
    at a (index.js:49)

**Comment by pvanroos** [comment]
I upgraded to 3id-connect@0.1.0 and now I get this at this line,  const authProvider = new EthereumAuthProvider(ethProvider, addresses[0]):

App.js:29 Uncaught (in promise) TypeError: _3id_connect__WEBPACK_IMPORTED_MODULE_5__.EthereumAuthProvider is not a constructor
    at authenticate0 (App.js:29)

**Comment by oed** [comment]
@pvanroos make sure you got the latest 3id-connect version by installing: `3id-connect@next`. Looks like you had the correct version at first: `3id-connect@1.0.0-alpha15`.
@zachferland can probably help you more.
