### ISSUE TITLE
Move modal app into management app

### ISSUE THREAD

**Issue by zachferland** [ceramicstudio/3id-connect#150]
Should be as simple as moving the files over and some configuration. Only requirement is that each 'page' is loaded separately, so that the existing management page is not loaded on load, but only when needed.

**Comment by mwufi** [comment]
hey, I'm getting some errors starting the app

```
TypeError: (0 , _3id_common__WEBPACK_IMPORTED_MODULE_0__.isValidNetwork) is not a function
```

does that happen??

**Comment by Sterahi** [comment]
hey @mwufi can you bring this over to our discord? we prefer to do assistance there as it gets more of the teams eyes on it. https://chat.ceramic.network
