### ISSUE TITLE
Migrate an existing 3Box profile to IDX on first connect

### ISSUE THREAD

**Issue by dysbulic** [ceramicstudio/3id-connect#18]
I spoke to @michaelsena on Discord and they said that when a user first authenticates using 3ID Connect eventually it will automatically migrate their 3Box profile to IDX.

I'm just creating this issue to track the progress of that since [MyMeta](//my.metagame.wtf) already has everyone using 3Box, and until that information can be migrated we're blocked on the migration to IDX.

**Comment by oed** [comment]
We will keep you updated @dysbulic!

**Comment by oed** [comment]
Fyi, the integration is being tracked here: https://github.com/ceramicstudio/3id-connect/pull/20

Still depends on the Ceramic fire mainnet before the 3Box profiles will be migrated though. However, once the code is in place from the ticket above, the integration could be tested out.
