### ISSUE TITLE
Use blockchain-utils-linking from ceramic repo

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/3id-connect#19]
Now it makes sense to replace 3id-blockchain-utils with linking utils from ceramic repo.

Reasons:
- 3id-blockchain-utils package is effectively deprecated AFAIK,
- new linking utils package is lighter, thus making the resulting 3id-connect lighter too.

**Comment by oed** [comment]
@PaulLeCam added this to your sprint :)

**Comment by PaulLeCam** [comment]
@ukstv do you have more details please? I couldn't find docs for these packages or upgrade info from 3id-blockchain-utils.

**Comment by ukstv** [comment]
https://github.com/ceramicnetwork/js-ceramic/blob/develop/docs-src/guides/add-new-blockchain.md @PaulLeCam would this help?

**Comment by ukstv** [comment]
One thing: I think EthereumAuthProvider should be re-exported from 3id-connect to maintain backwards compatibility.

**Comment by ukstv** [comment]
Hmm, re-exported along with other auth providers.

**Comment by oed** [comment]
See here as well: https://developers.ceramic.network/reference/typescript/modules/_ceramicnetwork_blockchain_utils_linking.html

**Comment by PaulLeCam** [comment]
OK thanks, are the APIs the same please? I'm not familiar with these packages and the API docs are not very helpful to identify this (`createLink(did: string, account: AccountID, provider: any, opts: any)` gives me no clue what a valid provider or options should be for example).

**Comment by ukstv** [comment]
@PaulLeCam This one is part of an auth provider: https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/blockchain-utils-linking/src/ethereum.ts#L45
