### ISSUE TITLE
Self.id profile edit does not work 

### ISSUE THREAD

**Issue by joanna2028** [ceramicstudio/3id-connect#228]
# Whats the point to create a public Id DID:... if we can not edit completely our profile and save it 

Provide a 2-3 sentence overview of the work to be done.

# Technical Information

Letter country code do not allow to save it, if you let this in blank so then yes. Weird

**Comment by stbrody** [comment]
Hi @JoannaPicetti, if you're having trouble updating your profile on self.id, please share the actual error you are seeing so we can take a look.

**Comment by joanna2028** [comment]
Thank you for your response Spencer.

When I complete the country (I tried with so many) appear this: Failed to
save profile

Not number of error, impossible to track what is happening


[image: Screen Shot 2022-02-18 at 15.26.05.png]

**Comment by PaulLeCam** [comment]
@JoannaPicetti what country code are you trying to set please?
The basic profile schema only supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).

**Comment by stbrody** [comment]
also @JoannaPicetti, it looks like you tried to attach a screenshot but it didn't come through.  If you do have a screenshot of the error from the browser developer console that would be helpful to see

**Comment by joanna2028** [comment]
I think is time to create a new institution for standarization.


.EARTH for all the Nations.


ISO 3166-1 alpha-2  is from 1974, those codes are too old. Was created before the launch of WWW.

**Comment by joanna2028** [comment]
> also @JoannaPicetti, it looks like you tried to attach a screenshot but it didn't come through. If you do have a screenshot of the error from the browser developer console that would be helpful to see

I sent you by email.

**Comment by stbrody** [comment]
> > also @JoannaPicetti, it looks like you tried to attach a screenshot but it didn't come through. If you do have a screenshot of the error from the browser developer console that would be helpful to see
> 
> I sent you by email.

Sorry, I don't think I got it.  If you can upload it to this github issue that would be best so other engineers on our team can take a look as well

**Comment by JoannaPicetti** [comment]
@stbrody  Here it goes

file:///Users/jp/Desktop/Failed%20to%20save%20profile%20-%20Self.id.png

**Comment by stbrody** [comment]
> @stbrody Here it goes
> 
> file:///Users/jp/Desktop/Failed%20to%20save%20profile%20-%20Self.id.png

still didn't work, we're just getting the uri to the file on your harddrive, not the actual image itself.  You may want to upload the image to an image hosting service service like https://imgbb.com/ and post the resulting URL here

**Comment by JoannaPicetti** [comment]
Got it, thanks!

**Comment by PaulLeCam** [comment]
@JoannaPicetti can you try setting the country code in uppercase please?
We'll update the logic to do this automatically in self.id but in the meantime this should solve your issue.

**Comment by joanna2028** [comment]
> > @stbrody Here it goes
> > file:///Users/jp/Desktop/Failed%20to%20save%20profile%20-%20Self.id.png
> 
> still didn't work, we're just getting the uri to the file on your harddrive, not the actual image itself. You may want to upload the image to an image hosting service service like https://imgbb.com/ and post the resulting URL here

Here it goes,


BBCode full linked / 


[url=[https://ibb.co/R67fJ0j][img]https://i.ibb.co/DMLhjCr/Screen-Shot-2022-02-25-at-10-07-28.png[/img][/url]](https://ibb.co/R67fJ0j%5D%5Bimg%5Dhttps://i.ibb.co/DMLhjCr/Screen-Shot-2022-02-25-at-10-07-28.png%5B/img%5D%5B/url%5D)

**Comment by joanna2028** [comment]
Just in case,

https://ibb.co/R67fJ0j

<img width="791" alt="Screen Shot 2022-02-25 at 10 14 37" src="https://user-images.githubusercontent.com/62726639/155721269-1c5a3c9d-771a-4cc9-88fc-c1b548dd58c3.png">

**Comment by joanna2028** [comment]
<img width="910" alt="Screen Shot 2022-02-25 at 10 07 28" src="https://user-images.githubusercontent.com/62726639/155721408-8d55a87a-1f98-4109-8667-3036f30e78e4.png">

**Comment by joanna2028** [comment]
we can connect just with ETHEREUM 

it will be possible to connect with all the networks ?

<img width="1177" alt="Screen Shot 2022-02-25 at 09 43 53" src="https://user-images.githubusercontent.com/62726639/155721833-22395720-bfe9-41b5-baf7-c5af625ee25e.png">
?

**Comment by joanna2028** [comment]
> I think is time to create a new institution for standarization.
> 
> .EARTH for all the Nations.
> 
> ISO 3166-1 alpha-2 is from 1974, those codes are too old. Was created before the launch of WWW.

I insist, we need new standars

**Comment by PaulLeCam** [comment]
Closing as this is fixed in the deployed version of self.id
