### ISSUE TITLE
DID is not getting authenticated using 3id-connect and EthereumAuthProvider

### ISSUE THREAD

**Issue by asnal** [ceramicstudio/3id-connect#230]
# Description

I am trying to authenticate a DID using 3id-connect and set a basicProfile but at `await ceramic.did.authenticate()` i am getting this error on the console:
did.ts:260 Uncaught (in promise) TypeError: did_jwt_1.verifyJWS is not a function
    at DID.<anonymous> (did.ts:260:1)
    at Generator.next (<anonymous>)
    at fulfilled (resolver.ts:226:1)
Here is the code snippet:

    `const [address] = await window.ethereum.request({
      method: 'eth_requestAccounts'
      })
    const ceramic = new CeramicClient(endpoint)

    const threeIdConnect = new ThreeIdConnect()

    const provider = new EthereumAuthProvider(window.ethereum, address)

    await threeIdConnect.connect(provider)
    const did = new DID({
      provider: threeIdConnect.getDidProvider(),
      resolver: {
        ...ThreeIdResolver.getResolver(ceramic)
      }
    })
    console.log("DID:",did)
    ceramic.setDID(did)
    await ceramic.did.authenticate()`

**Comment by PaulLeCam** [comment]
@asnal what versions of the dependencies are you using please? Could you provide an example setup to reproduce the issue?

**Comment by asnal** [comment]
@PaulLeCam the issue was resolved by what @Sterahi suggested on discord. She also mentioned that these bugs will be fixed in future releases. If you want i can close the issue for now.
