### ISSUE TITLE
support local node with `--network=inmemory`

### ISSUE THREAD

**Issue by shanejonas** [ceramicstudio/3id-connect#24]
**Describe the problem**
`3id-connect` currently only works with the Clay Testnet. As a developer, I would like to be able to get a fully isolated dev set up working.

![image](https://user-images.githubusercontent.com/364566/107097972-f95efb80-67c2-11eb-9685-e87dea8fb688.png)

**steps to reproduce**
1. run `ceramic daemon --network=inmemory`
2. run `CERAMIC_API=http://localhost:7007 npm run start` in `3id-connect`
3. set https://github.com/ceramicstudio/web-playground to use local node + local 3id-connect
4. timeout errors

**Comment by oed** [comment]
@PaulLeCam @zachferland can you have a look at this? Is @shanejonas doing something wrong, or is this a missing feature in 3id-connect?

**Comment by PaulLeCam** [comment]
I haven't been able to have a working integration tests setup using the `inmemory` network of Ceramic, if I remember correctly it didn't behave as expected compared to using the default settings, so I think that's the main issue.
The build process for 3ID Connect properly handles the `CERAMIC_API` environment variable as far as I can tell, considering I'm using it to create custom builds for the integration tests.
