### ISSUE TITLE
ThreeIdConnect connect method doesn't resolve after iframeLoadedPromise called.

### ISSUE THREAD

**Issue by cnsndnz** [ceramicstudio/3id-connect#244]
Hi, 

The issue happens in my next.js app. ThreeIdConnect.connect method doesn't resolve after calling it. It was working few days ago but it started to failing today. I have checked the provided values and didn't see any problem with them. 

**UPDATE: This issue happens only in the latest version of Chrome. There is no problem with Firefox.**

```
this.ceramic = new CeramicClient(endpoint);
const threeIdConnect = new ThreeIdConnect();
const authProvider = new EthereumAuthProvider((window as any).ethereum, account);
await threeIdConnect.connect(authProvider); // Connect method doesn't resolve
```

When I check the @3id/connect source code from browser I see that it stucks on iframeLoadedPromise method given below.

```
// onload event never triggers here 
this.iframeLoadedPromise = new Promise((resolve)=>{
            this.iframe.onload = ()=>{
                resolve();
            };
        });

 async connect(provider) {
        if (this._authProviderSubscription) {
            this._authProviderSubscription.unsubscribe();
        }
        if (provider) {
            await this.setAuthProvider(provider);
        }
        await this.iframeLoadedPromise;
        // TODO: this should only be set if there is a provider injected, also need to stop current subscription
        this._authProviderSubscription = createAuthProviderServer(provider).subscribe();
        createDisplayConnectServerRPC(this.iframe).subscribe();
        createDisplayManageServerRPC(this.manageUrl).subscribe();
        this._connected = true;
    }
```

I'm using the latest version.

```
    "@3id/connect": "^0.4.1",
    "@ceramicnetwork/3id-did-resolver": "^2.0.0",
    "@ceramicnetwork/http-client": "^2.0.0",
    "@ceramicnetwork/stream-tile": "^2.0.0",
    "@ceramicstudio/idx": "^0.12.2",
    "@ethersproject/providers": "^5.6.4",
    "@web3-react/coinbase-wallet": "^8.0.22-beta.0",
    "@web3-react/core": "^6.1.9",
    "@web3-react/injected-connector": "^6.0.7",
    "@web3-react/metamask": "^8.0.0-beta.0",
    "@web3-react/types": "^6.0.7",
    "axios": "^0.27.2",
    "did-resolver": "^3.2.0",
    "dids": "^3.1.0",
```

**Comment by avious00** [comment]
Hey @cnsndnz, I'm the developer-facing Product Manager. We've got your issue captured in our backlog and one of our engineers will be reaching out to you shortly. Thank you for your patience and detailed notes (code snippets and trying in different browsers)!

By the way, it looks like you just got into web3 recently? Would love to hear what you're interested in and working on.

**Comment by cnsndnz** [comment]
Hi @3avi, Thanks for the help. Yes, I've been interested in web3 recently, we are moving our application [index.as](https://index.as/) to web3 using ceramic, gnosis safe and lit protocol. We really appreciate what you're doing and will be happy to keep in touch.

**Comment by zachferland** [comment]
hey sorry for not following up earlier, do you still have the same issue? 

it is hasnt been reported by anyone else in the mean time, iframes some times do have different restrictions depending on the browser and/or configuration/settings

you may want to consider using did-session, as this will very soon be the suggested auth method over 3id-connect, and the best supported library. Early docs are here - https://developers.ceramic.network/reference/glaze/modules/did_session/ and there will be more info on that stack in the coming weeks

**Comment by avious00** [comment]
@cnsndnz some more context on auth: the new Ceramic did-session library pairs with Sign-In With Ethereum https://login.xyz/ - a web3 wide initiative to sign in with your wallet to apps. more secure and user friendly than 3ID connect!

**Comment by zachferland** [comment]
Closing, please open a new issue for any follow up.
