### ISSUE TITLE
Multiple 'did' creation

### ISSUE THREAD

**Issue by lyd0** [ceramicstudio/3id-connect#247]
# Description

An address already has a did. Execute the method in the screenshot again, and why does this address have a low probability of returning a new did?

![image](https://user-images.githubusercontent.com/29918052/178397492-8f09e740-9399-4831-b580-c83603fb8f89.png)

# Technical Information

```
async _initIdentity(config: AuthConfig | SeedConfig): Promise<string> {
    // Same request relayed before idw handles it, if request reaches idw, then permission given
    const getPermission = () => Promise.resolve([])

    const threeIdConfig = Object.assign(config, {
      getPermission,
      ceramic: this.ceramic,
    })
    const threeId = await ThreeIdProvider.create(threeIdConfig)
    this.threeIdProviders[threeId.id] = threeId
    await this.store.storeDID(threeId.id, this.threeIdProviders[threeId.id].keychain.keyring.seed)
    return threeId.id
  }
 
```

**Comment by lyd0** [comment]
@zachferland @PaulLeCam Hi, How can I solve this problem please? How can I not create a new 'did'

**Comment by PaulLeCam** [comment]
This is the expected behavior, if the 3ID provider doesn't find an existing CAIP-10 link in the network for the given address, a new DID is created.

**Comment by lyd0** [comment]
> This is the expected behavior, if the 3ID provider doesn't find an existing CAIP-10 link in the network for the given address, a new DID is created.

However, the metamask account I am logged into has a did account and I was able to log in normally before, but by chance a new did was created by logging in.
Is this a problem caused by a node error (e.g. network problem)?

**Comment by PaulLeCam** [comment]
Yes it could be due to a network error if the node storing the stream isn't responsive.
