### ISSUE TITLE
Migrating existing 3ID fails with invalid signature

### ISSUE THREAD

**Issue by codynhat** [ceramicstudio/3id-connect#63]
**Describe the bug**
Receiving a failure when trying to connect an existing 3ID in `0.1.3`

**To Reproduce**
1. Via the [web playground](https://github.com/ceramicstudio/web-playground) connect a wallet that has an existing 3ID
2. Select "Continue" when prompted "The site wants to access your personal data"
3. Select "Continue" when prompted "Your 3Box DID <> will be migrated"
4. Sign two messages in wallet
5. Receive error "Unable to connect"

**Expected behavior**
No error is expected.

**Versions** 
Produced using the web playground using `@3id/connect@0.1.3`

**Screenshots**
<img width="1334" alt="Screen Shot 2021-05-13 at 10 20 41" src="https://user-images.githubusercontent.com/6885592/118163229-9c34a080-b3d6-11eb-99f9-a57517a9ca4d.png">
<img width="1354" alt="Screen Shot 2021-05-13 at 10 20 48" src="https://user-images.githubusercontent.com/6885592/118163241-9fc82780-b3d6-11eb-9c11-a9b9ce91b9ed.png">
<img width="1208" alt="Screen Shot 2021-05-13 at 10 21 16" src="https://user-images.githubusercontent.com/6885592/118163249-a191eb00-b3d6-11eb-8bb3-b87d03a9922a.png">

**Additional context**
- Same error was received using the same 3id-connect version in a different app
- I'm not sure if the 3ID I'm attempting with had an old 3Box profile, or a not-so-old 3ID from Ceramic < 1.0

**Comment by oed** [comment]
@zachferland seems like there may be a bug in the migration flow?
@ukstv maybe you can help looking into this?

**Comment by codynhat** [comment]
I believe this is fixed in `0.1.4`. Can anyone else confirm?

**Comment by ukstv** [comment]
@codynhat Fixed in 0.1.4, web-playground now uses it. Please, check out.

**Comment by codynhat** [comment]
Confirmed I am no longer seeing this. I think we can close it?

**Comment by ukstv** [comment]
We can, we do.
