### ISSUE TITLE
Add option to skip migration and just create new account

### ISSUE THREAD

**Issue by oed** [ceramicstudio/3id-connect#64]
Sync with @zachferland on exactly what to do!

**Comment by zachferland** [comment]
@ukstv I ended up starting this today, can pick this up now without the gateway work

**Comment by zachferland** [comment]
Implemented the following: 

- on any uncaught error during the migration, the user is prompted with and additional migration fail prompt asking them if they want to continue by create a new did instead. 

- separated core did migration failures from link/data migration failures, if did succeeds, but fails during link/data 3id-connect will resolve now and just create a new link instead. Existing data could that failed could also be migrated a later point. 

- log failures during migration, if we need to debug any account migrations

Added - https://github.com/ceramicstudio/3id-connect/issues/67 as an additional option to improve user experience
