### ISSUE TITLE
Default migration paths for known failures 

### ISSUE THREAD

**Issue by zachferland** [ceramicstudio/3id-connect#67]
Due to past bugs in 3box, there is a few instances where it is not easy to migrate the dids. As implemented the migration will just fail with error, and then reprompt user to create a new instead. 

For known failures we can detect ahead of time, we could instead just default to creating a new did without any migration prompts. This is likley best.

Example of an account we cant easily migrate

DID owned by ADDRESS_ONE
https://ipfs.3box.io/did-doc?cid=bafyreihggvtidyvqw42hitvj3veki7wmhnchuok5mcjlosgu5532mrkcya

LINK DID -> ADDRESS_TWO 
https://beta.3box.io/address-server/odbAddress/0x12396e8b57b1a64ed18aa6fc2f5fec75ba55de07

It is diffucult to make any default choices about migration (other than just create new), since the user may not want ADDRESS_TWO profile added to ADDRESS_ONE, this may have been linked by accident. And unfortunately when authenticating with ADDRESS_ONE no link will be found and a new did will be created anyways

**Comment by oed** [comment]
> And unfortunately when authenticating with ADDRESS_ONE no link will be found and a new did will be created anyways

I don't think this is always the case. I've seen multiple 3Box accounts that have two addresses linked to them.

**Comment by zachferland** [comment]
@oed well multiple links in orbitdb (which doesnt really help lookups), but the address server will only have a single mapping

**Comment by zachferland** [comment]
Also muport dids fall underneath this category, can be detect ahead of of time, they dont migrate now and we dont catch failures here. Likely not feasible to migrate these (technically possible though), should likely just default to creating new dids without any prompts

**Comment by zachferland** [comment]
Additionally, if new dids are created for muport dids, we can still choose to migrate just the profile data (not social/address links)

**Comment by oed** [comment]
@zachferland when you say that ppl have muport dids you mean for the social verifications specifically? I assume they still have a 3id?

**Comment by zachferland** [comment]
no, generally, i dont remember the migration/path support there though 
for example - https://beta.3box.io/address-server/odbAddress/0x8f942eced007bd3976927b7958b50df126feecb5

**Comment by oed** [comment]
Ok, not sure exactly.

**Comment by zachferland** [comment]
reminded me, i do also wonder if some of the invalid signature errors on migration are muport social links on 3ids, going to also check that
