### ISSUE TITLE
Link button should indicate progress

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/3id-connect#69]
It takes time to invoke MetaMawk and load data. While it happens a user is in limbo. Unclear what is happening.

<img width="892" alt="Screenshot 2021-05-19 at 20 07 01" src="https://user-images.githubusercontent.com/193527/118855070-133dcd80-b8de-11eb-8d2b-c82a12cfe6fe.png">

**Comment by zachferland** [comment]
👍  yeah same with other buttons here, like create
