### ISSUE TITLE
"Stay connected" option

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/3id-connect#71]
Add a "Stay connected" option in the prompt so that 3ID Connect would persist the last time this consent prompt showed up and only ask for consent again at a certain frequency (every 2 weeks for example).

**Comment by yjkimjunior** [comment]
+1

**Comment by zachferland** [comment]
@yjkimjunior this was a bug, the latest 3id-connect iframe release (a few days ago) includes a fix. The expected behavior now is to only see the permission modal the first time a user connects to an app (or when permission not stored locally). Then the user should not see the modal.

**Comment by zachferland** [comment]
Keeping this issue open though, more granular config options may make sense here in future. Ie, always, only first time, and as mentioned, permission expirations.

**Comment by yjkimjunior** [comment]
> Keeping this issue open though, more granular config options may make sense here in future. Ie, always, only first time, and as mentioned, permission expirations.

awesome, thanks for the hustle!
