### ISSUE TITLE
Key cache state

### ISSUE THREAD

**Issue by zachferland** [ceramicstudio/3id-connect#77]
Currently: 
caip10 -> did 
did -> seed 

Not freindly for key rotations, auth data may not be necessarily either. Need to change implementation once key rotations are more widely supported and/or make additional network requests.

**Comment by oed** [comment]
Should be `caip10 -> authSecret` right?

**Comment by zachferland** [comment]
Im assuming not necessarily, how currently implemented yes, but seems like may add/remove and change authsecrets during a key rotation as well in many cases.
