### ISSUE TITLE
BUG: Error: Unable to connect

### ISSUE THREAD

**Issue by abhisingh3195** [ceramicstudio/3id-connect#79]
**Describe the bug**
 Error: Unable to connect on ceramic popup

**To Reproduce**
1. Using package '@3id/connect'
2. Connecting with 3id with the following code
```
import { ThreeIdConnect, EthereumAuthProvider } from '@3id/connect'
const threeIdConnect = new ThreeIdConnect()
let authProvider = new EthereumAuthProvider(window.ethereum, address)
yield threeIdConnect.connect(authProvider)
const didProvider = yield threeIdConnect.getDidProvider()
const CERAMIC_URL = "https://ceramic-clay.3boxlabs.com";
const ceramic = new Ceramic(CERAMIC_URL)
yield ceramic.setDIDProvider(didProvider)
```

**Screenshots**
Pic 1 - These APIs are getting called only, after which i get the error in Pic 2
![Screenshot from 2021-06-07 11-56-45](https://user-images.githubusercontent.com/62532644/120992703-7a91c380-c7a0-11eb-9cfc-8215db366b12.png)

Pic 2
![Screenshot from 2021-06-07 11-56-53](https://user-images.githubusercontent.com/62532644/120992725-7f567780-c7a0-11eb-9d56-6e49782b37ed.png)

Pic 3 and Pic 4 - Getting error on this API only for now but still other APIs are getting called which further gives the error on popup.
![Screenshot from 2021-06-07 13-08-15](https://user-images.githubusercontent.com/62532644/120992744-83829500-c7a0-11eb-8e0a-36464702e2c5.png)
![Screenshot from 2021-06-07 13-08-27](https://user-images.githubusercontent.com/62532644/120992755-87161c00-c7a0-11eb-8ac3-e9dfab4da1e8.png)

**Ceramic versions** 
"@3id/connect": "^0.1.3",
"@ceramicnetwork/http-client": "^0.9.3",
"@ceramicstudio/idx": "^0.7.0",

**Machine, OS, browser information (please complete the following information):**
Linux,testing on Chrome and Brave only for right now.

**Comment by oed** [comment]
Thanks @abhisingh3195, do you see any other errors on the developer console?

**Comment by abhisingh3195** [comment]
Yes @oed ,you can refer to this screenshot

![Screenshot from 2021-06-07 15-31-11](https://user-images.githubusercontent.com/62532644/120998261-8cc23080-c7a5-11eb-95e0-300e477da939.png)

**Comment by oed** [comment]
@abhisingh3195 could you copy paste the DID from the error above? Want to have a closer look

**Comment by abhisingh3195** [comment]
Sure @oed , here did:3:kjzl6cwe1jw149bzumoqo75tpr60ewz05auluqezuto1cz4fdgsmmslzijlwqjz

**Comment by oed** [comment]
I'm also curious if you are seeing this for all accounts, or only specific ones.

If it's only specific ones then this issue is limited to the brokne accounts only.

> Sure @oed , here did:3:kjzl6cwe1jw149bzumoqo75tpr60ewz05auluqezuto1cz4fdgsmmslzijlwqjz

Can you please also include the `version-id` query param

**Comment by abhisingh3195** [comment]
@oed This one we are seeing on all accounts, even the ones which we have just created now.

Error with version id - 
Error: Error: Failed to resolve did:3:kjzl6cwe1jw149bzumoqo75tpr60ewz05auluqezuto1cz4fdgsmmslzijlwqjz?version-id=0#2KR7X95z5P76V3x: invalidDid, TypeError: Cannot read property 'content' of undefined

and with new account that i just created - 
Error: Error: Failed to resolve did:3:kjzl6cwe1jw14aizpwy2m6fr6e5xtceihhowbwx7lknsmatcx0qz4fx90izk2rn?version-id=0#T9vM9y8uUf6eUMH: invalidDid, TypeError: Cannot read property 'content' of undefined

**Comment by ukstv** [comment]
@abhisingh3195 Hey, can I ask you to clear local storage for both the page you are on and the 3id iframe? Do you still have the same issue after the cleaning?

**Comment by oed** [comment]
Interesting @ukstv My broken account started working after I cleared the cache on `https://app-clay.3idconnect.org`!

**Comment by abhisingh3195** [comment]
@ukstv Yes, i tried but i was still getting the issue, will ask my team also to do the same tomorrow and will let you know.

**Comment by oed** [comment]
@abhisingh3195 I'm able to resolve both of the DIDs you posted above now. Can you check again to see if it's working or not?

**Comment by abhisingh3195** [comment]
@oed @ukstv Yes it's resolved now. Thanks.

**Comment by ukstv** [comment]
Cool. Closing the issue now.
